services:
  changedetection.io:
    container_name: changedetection.io
    restart: unless-stopped
    ports:
      - 5555:5000
    environment:
      - PLAYWRIGHT_DRIVER_URL=ws://192.168.1.36:5556?stealth=1&--disable-web-sec                                                                                                                                                             urity=true
    volumes:
      - /home/pi/changedetection:/datastore
    image: ghcr.io/dgtlmoon/changedetection.io:dev
  playwright-chrome:
    hostname: playwright-chrome
    image: browserless/chrome:latest
    restart: unless-stopped
    ports:
      - 5556:3000
    environment:
      - MAX_CONCURRENT_SESSIONS=11
